// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlBdQ25718rLbbj3labd71N9wXhSaASo0',
    appId: '1:588474215278:web:74c5dd78335489f3c1ef7f',
    messagingSenderId: '588474215278',
    projectId: 'vista-social-media-app',
    authDomain: 'vista-social-media-app.firebaseapp.com',
    storageBucket: 'vista-social-media-app.appspot.com',
    measurementId: 'G-L20R28Z7TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAplAczvKe-YH9GpCKP7EoaPTadd3YZi0I',
    appId: '1:588474215278:android:d5494d791e2f0474c1ef7f',
    messagingSenderId: '588474215278',
    projectId: 'vista-social-media-app',
    storageBucket: 'vista-social-media-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1gFYzw9zBaFXIwlC8h36aVE4wUDrPv5w',
    appId: '1:588474215278:ios:065c6a1191256172c1ef7f',
    messagingSenderId: '588474215278',
    projectId: 'vista-social-media-app',
    storageBucket: 'vista-social-media-app.appspot.com',
    iosBundleId: 'com.example.vistaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1gFYzw9zBaFXIwlC8h36aVE4wUDrPv5w',
    appId: '1:588474215278:ios:dbdc3fd046772021c1ef7f',
    messagingSenderId: '588474215278',
    projectId: 'vista-social-media-app',
    storageBucket: 'vista-social-media-app.appspot.com',
    iosBundleId: 'com.example.vistaApp.RunnerTests',
  );
}
